In [4]:
import numpy as np

* Numpy is a nultdim arraya

In [8]:
! pip install numpy

Access is denied.


In [9]:
import math
math.sqrt(4)

2.0

In [11]:
l =[1,2,3,4,"hello"]
import numpy
numpy.array([l])

array([['1', '2', '3', '4', 'hello']], dtype='<U21')

In [12]:
import numpy as np

In [13]:
# Numpy -> its a multidimensional array librabry.i,e u can store all store of data.link

Numpy -> #its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;

Numpy -> #its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;

In [ ]:
#THE BASICS :

#initialize array

#THE BASICS :

#initialize array

In [14]:


#initialize array
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

one dimensional array : [1 2 3]


In [15]:
b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [17]:
#Get Dimension

#Get Dimension

print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)


In [18]:
print("dimension of a :",a.ndim)


dimension of a : 1


In [ ]:
#Get Shape

In [30]:
#Get Shape

#Get Shape

print("shape of a :",a.shape) 
#its a vector so its tellings us one dimension 
print("shape of b :",b.shape)


print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)


In [31]:
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)


shape of a : (3,)
shape of b : (2, 4)


In [32]:
#Get  Type

#Get  Type

In [33]:
print("a type is :",a.dtype)

a type is : int16


In [ ]:
#Get Size


#Get Size

In [34]:
print("size of a :",a.size) # # of element in the array.i,e length of array;

size of a : 3


In [ ]:
#total size

#total size

In [35]:
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)

a item size : 2
total size is a: 6


In [ ]:
#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

In [ ]:
#Get specific element [row,column] -ve index is possible similar to list;

#Get specific element [row,column] -ve index is possible similar to list;

In [36]:
b[1,2]

np.float64(4.2)

In [ ]:
#Get specific row [row,:]#we use slicing(:) operation

#Get specific row [row,:]#we use slicing(:) operation

In [37]:
print("row :",b[1,0:1]);

row : [2.1]


In [ ]:

#Get specific column[:,column]


#Get specific column[:,column]

In [39]:
print("column :",b[:,1])

column : [2. 3.]


In [ ]:
#Get Dimension

#Get Dimension

In [40]:
print("subset of specific row",b[1,1::2])

subset of specific row [3.  4.5]


In [ ]:
#change element

#change element

In [41]:
b[1,2]=8
print(b)

b[:,2]=[9,4]
b

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

In [ ]:
3-d Example

3-d Example

In [46]:
c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])



In [47]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [48]:
type(c)

numpy.ndarray

In [50]:
c.ndim

3

In [51]:
c.shape

(2, 2, 2)

In [52]:
c= np.array([[[1,2,7],[3,4,9]],[[5,6,6],[7,8,4]]])

In [53]:
c.size

12

In [54]:
c.shape

(2, 2, 3)

In [ ]:
# calculate the memory space took for c numpy array

# calculate the memory space took for c numpy array

In [55]:
c.dtype

dtype('int64')

In [56]:
c.itemsize*c.size

96

In [57]:
#get specific element (work outside in)
print("specified element is:",c[0,0,0,])

specified element is: 1


In [58]:
#get specific element (work outside in)
print("specified element is:",c[0,1,1,])

specified element is: 4


In [60]:
c[0,1,1,]=100

In [61]:
c

array([[[  1,   2,   7],
        [  3, 100,   9]],

       [[  5,   6,   6],
        [  7,   8,   4]]])

In [ ]:
#Initializing different types of arrays

#Initializing different types of arrays

np.zeros((3,4))

In [ ]:
np.zeros((3,4)) #3 rows and columns


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
zm = np.zeros((3,4))

In [64]:
zm.ndim

2

In [65]:
zm.shape

(3, 4)

In [ ]:
# all 1's matrix

# all 1's matrix

In [66]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
 ones = np.ones((4,3),dtype="int16")

In [72]:
ones[1,1]=100
ones

array([[  1,   1,   1],
       [  1, 100,   1],
       [  1,   1,   1],
       [  1,   1,   1]], dtype=int16)

In [73]:
#any ather matrix/numbers
np.full(ones.shape,88,dtype="float")

array([[88., 88., 88.],
       [88., 88., 88.],
       [88., 88., 88.],
       [88., 88., 88.]])

In [ ]:
np.full(4,5),88)

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [79]:
m100=np.full((6,5),100,dtype="float")

In [ ]:
result the already existing array and assign one value to

result the already existing array and assign one value to

In [81]:
np.full_like(m100,200,dtype="float")

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

#Random matrix

In [82]:
np.random.random_sample((2,3))

array([[0.7161606 , 0.50499675, 0.47963978],
       [0.47879111, 0.61216442, 0.02420984]])

In [83]:
np.random.rand(2,3)

array([[0.62717905, 0.42124308, 0.494037  ],
       [0.19135238, 0.00387786, 0.80268098]])

In [84]:
np.random.randint(6,9,size=(3,3))

array([[8, 6, 7],
       [6, 7, 7],
       [6, 6, 8]], dtype=int32)

In [85]:
#denarate identity matrix only one arg bcoz identity matrix is quere matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])